// DO NOT EDIT! Autogenerated by HLA tool

public class GateDurabilityMarker
{
    public int Value { get; }

    public GateDurabilityMarker(int value)
    {
        Value = value;
    }

    public override string ToString()
    {
        return Value.ToString();
    }

    public static GateDurabilityMarker operator +(GateDurabilityMarker a, GateDurabilityMarker b)
    {
        return new GateDurabilityMarker(a.Value + b.Value);
    }

    public static GateDurabilityMarker operator -(GateDurabilityMarker a, GateDurabilityMarker b)
    {
        return new GateDurabilityMarker(a.Value - b.Value);
    }

    public static GateDurabilityMarker operator *(GateDurabilityMarker a, GateDurabilityMarker b)
    {
        return new GateDurabilityMarker(a.Value * b.Value);
    }
}

public class CreatureCardId
{
    public string Value { get; }

    public CreatureCardId(string value)
    {
        Value = value;
    }

    public override string ToString()
    {
        return Value;
    }
}

public class CreatureCard
{
    private string id;

    private CreatureCard(string id)
    {
        this.id = id;
    }

    public CreatureCardId GetId()
    {
        return new CreatureCardId(this.id);
    }

    public static CreatureCard Create(CreatureCardId id)
    {
        return new CreatureCard(id.Value);
    }
}

public class GateCard
{
    private bool destroyed;

    private GateCard(bool destroyed)
    {
        this.destroyed = destroyed;
    }

    public bool GetDestroyed()
    {
        return this.destroyed;
    }

    public static GateCard Create(bool destroyed)
    {
        return new GateCard(destroyed);
    }
}

public class GateDurabilityCard
{
    private int myMarker;
    private int opponentMarker;

    private GateDurabilityCard(int myMarker, int opponentMarker)
    {
        this.myMarker = myMarker;
        this.opponentMarker = opponentMarker;
    }

    public GateDurabilityMarker GetMyMarker()
    {
        return new GateDurabilityMarker(this.myMarker);
    }

    public GateDurabilityMarker GetOpponentMarker()
    {
        return new GateDurabilityMarker(this.opponentMarker);
    }

    public static GateDurabilityCard Create(GateDurabilityMarker myMarker, GateDurabilityMarker opponentMarker)
    {
        return new GateDurabilityCard(myMarker.Value, opponentMarker.Value);
    }
}