// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.carddrawing.api

import com.github.bratek20.ostium.kaijugame.api.*

interface CardDrawer {
    fun draw(): Card
}

interface CardDrawerFactory {
    fun create(): CardDrawer
}