// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.kaijugame.context

import com.github.bratek20.architecture.context.api.ContextBuilder
import com.github.bratek20.architecture.context.api.ContextModule
import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig
import com.github.bratek20.infrastructure.httpserver.api.WebServerModule

import com.github.bratek20.ostium.kaijugame.api.*
import com.github.bratek20.ostium.kaijugame.web.*

class KaijuGameWebClient(
    private val config: HttpClientConfig
): ContextModule {
    override fun apply(builder: ContextBuilder) {
        builder
            .setImplObject(KaijuGameWebClientConfig::class.java, KaijuGameWebClientConfig(config))
            .setImpl(GameApi::class.java, GameApiWebClient::class.java)
    }
}

class KaijuGameWebServer: WebServerModule {
    override fun apply(builder: ContextBuilder) {
        builder.withModule(KaijuGameImpl())
    }

    override fun getControllers(): List<Class<*>> {
        return listOf(
            GameApiController::class.java,
        )
    }
}