// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesmanagement.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.ostium.gamesmanagement.api.*

fun assertGameId(given: GameId, expected: Int) {
    val diff = diffGameId(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertCreatedGame(given: CreatedGame, expectedInit: ExpectedCreatedGame.() -> Unit) {
    val diff = diffCreatedGame(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}