// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using GamesManagement.Api;

namespace KaijuGame.Api {
    public enum DamageType {
        Light,
        Medium,
        Heavy,
    }

    public enum TurnPhase {
        PlayCard,
        AssignDamage,
        AssignGuard,
        Reveal,
    }

    public enum HitZonePosition {
        Left,
        Center,
        Right,
    }
}