// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Architecture.Exceptions;
using GamesManagement.Api;

namespace KaijuGame.Api {
    public class GameNotFoundException: ApiException {
        public GameNotFoundException(
            string message = ""
        ): base(message) {
        }
    }
}