// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using GamesManagement.Api;

namespace KaijuGame.Api {
    public interface GameApi {
        /// <exception cref="GameNotFoundException"/>
        GameState GetState(GameToken token);

        GameState EndPhase(GameToken token);

        GameState PlayCard(GameToken token, int handCardIdx);

        GameState AssignDamage(GameToken token, HitZonePosition zone, DamageType damageType);

        GameState AssignGuard(GameToken token, HitZonePosition zone, DamageType damageType);
    }
}