// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using User.Api;

namespace GamesManagement.Api {
    public interface GamesManagementApi {
        GameId Create(Username creator);

        void Join(Username joiner, GameId gameId);

        void Delete(GameId gameId);

        List<CreatedGame> GetAllCreated();
    }
}