// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using User.Api;

namespace GamesManagement.Api {
    public class GameId {
        public int Value { get; }

        public GameId(
            int value
        ) {
            Value = value;
        }

        public override bool Equals(object? obj) {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != this.GetType()) return false;
            return Value == ((GameId)obj).Value;
        }

        public override int GetHashCode() {
            return Value.GetHashCode();
        }
    }

    public class CreatedGame {
        readonly int id;
        readonly string creator;

        public CreatedGame(
            int id,
            string creator
        ) {
            this.id = id;
            this.creator = creator;
        }
        public GameId GetId() {
            return new GameId(id);
        }
        public Username GetCreator() {
            return new Username(creator);
        }
        public static CreatedGame Create(GameId id, Username creator) {
            return new CreatedGame(id.Value, creator.Value);
        }
    }
}