// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesetup.api

import com.github.bratek20.ostium.gamecomponents.api.*

interface GameSetupApi {
    fun startGame(): Game
}