// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesetup.api

import com.github.bratek20.ostium.gamecomponents.api.*

data class Table(
    private val gateDurabilityCard: GateDurabilityCard,
    private val attackRow: CreatureCard?,
    private val defenseRow: CreatureCard?,
    private val gateCard: GateCard,
) {
    fun getGateDurabilityCard(): GateDurabilityCard {
        return this.gateDurabilityCard
    }

    fun getAttackRow(): CreatureCard? {
        return this.attackRow
    }

    fun getDefenseRow(): CreatureCard? {
        return this.defenseRow
    }

    fun getGateCard(): GateCard {
        return this.gateCard
    }

    companion object {
        fun create(
            gateDurabilityCard: GateDurabilityCard,
            attackRow: CreatureCard?,
            defenseRow: CreatureCard?,
            gateCard: GateCard,
        ): Table {
            return Table(
                gateDurabilityCard = gateDurabilityCard,
                attackRow = attackRow,
                defenseRow = defenseRow,
                gateCard = gateCard,
            )
        }
    }
}

data class Hand(
    private val cards: List<CreatureCard>,
) {
    fun getCards(): List<CreatureCard> {
        return this.cards
    }

    companion object {
        fun create(
            cards: List<CreatureCard>,
        ): Hand {
            return Hand(
                cards = cards,
            )
        }
    }
}

data class Game(
    private val table: Table,
    private val hand: Hand,
) {
    fun getTable(): Table {
        return this.table
    }

    fun getHand(): Hand {
        return this.hand
    }

    companion object {
        fun create(
            table: Table,
            hand: Hand,
        ): Game {
            return Game(
                table = table,
                hand = hand,
            )
        }
    }
}