// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesetup.api

import com.github.bratek20.ostium.gamecomponents.api.*

data class Hand(
    private val cards: List<CreatureCard>,
) {
    fun getCards(): List<CreatureCard> {
        return this.cards
    }

    companion object {
        fun create(
            cards: List<CreatureCard>,
        ): Hand {
            return Hand(
                cards = cards,
            )
        }
    }
}

data class Table(
    private val creatureCard: CreatureCard,
    private val gateCard: GateCard,
    private val gateDurabilityCard: GateDurabilityCard,
) {
    fun getCreatureCard(): CreatureCard {
        return this.creatureCard
    }

    fun getGateCard(): GateCard {
        return this.gateCard
    }

    fun getGateDurabilityCard(): GateDurabilityCard {
        return this.gateDurabilityCard
    }

    companion object {
        fun create(
            creatureCard: CreatureCard,
            gateCard: GateCard,
            gateDurabilityCard: GateDurabilityCard,
        ): Table {
            return Table(
                creatureCard = creatureCard,
                gateCard = gateCard,
                gateDurabilityCard = gateDurabilityCard,
            )
        }
    }
}

data class Game(
    private val hand: Hand,
    private val table: Table,
) {
    fun getHand(): Hand {
        return this.hand
    }

    fun getTable(): Table {
        return this.table
    }

    companion object {
        fun create(
            hand: Hand,
            table: Table,
        ): Game {
            return Game(
                hand = hand,
                table = table,
            )
        }
    }
}