// DO NOT EDIT! Autogenerated by HLA tool

using System;
using SingleGame.Api;
using Xunit;

namespace GameComponents
{
    public static class Asserts
    {

        public static void AssertCreatureCardId(CreatureCardId given, string expected)
        {
            var diff = Diffs.DiffCreatureCardId(given, expected);
            Assert.True(diff == "", diff);
        }

        public static void AssertCreatureCard(CreatureCard given, Action<Diffs.ExpectedCreatureCard> expectedInit)
        {
            var diff = Diffs.DiffCreatureCard(given, expectedInit);
            Assert.True(diff == "", diff);
        }
    }
}