// DO NOT EDIT! Autogenerated by HLA tool

using System;
using SingleGame.Api;

namespace GameComponents
{
    public static class Builders
    {
        public static GateDurabilityMarker BuildGateDurabilityMarker(int value = 0)
        {
            return new GateDurabilityMarker(value);
        }

        public static CreatureCardId BuildCreatureCardId(string value = "someValue")
        {
            return new CreatureCardId(value);
        }

        public class CreatureCardDef
        {
            public string Id { get; set; } = "someValue";
        }

        public static CreatureCard BuildCreatureCard(Action<CreatureCardDef> init = null)
        {
            var def = new CreatureCardDef();
            init?.Invoke(def);
            return CreatureCard.Create(new CreatureCardId(def.Id));
        }

        public class GateCardDef
        {
            public bool Destroyed { get; set; } = false;
        }

        public static GateCard BuildGateCard(Action<GateCardDef> init = null)
        {
            var def = new GateCardDef();
            init?.Invoke(def);
            return GateCard.Create(def.Destroyed);
        }

        public class GateDurabilityCardDef
        {
            public int MyMarker { get; set; } = 0;
            public int OpponentMarker { get; set; } = 0;
        }

        public static GateDurabilityCard BuildGateDurabilityCard(Action<GateDurabilityCardDef> init = null)
        {
            var def = new GateDurabilityCardDef();
            init?.Invoke(def);
            return GateDurabilityCard.Create(
                BuildGateDurabilityMarker(def.MyMarker),
                BuildGateDurabilityMarker(def.OpponentMarker)
            );
        }
    }
}