// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using SingleGame.Api;

namespace GameComponents
{
    public static class Diffs
    {
        public static string DiffCreatureCardId(CreatureCardId given, string expected, string path = "")
        {
            return given.Value != expected ? $"{path}value {given.Value} != {expected}" : string.Empty;
        }

        public class ExpectedCreatureCard
        {
            public string Id { get; set; }
        }

        public static string DiffCreatureCard(CreatureCard given, Action<ExpectedCreatureCard> expectedInit, string path = "")
        {
            var expected = new ExpectedCreatureCard();
            expectedInit?.Invoke(expected);
            var result = new List<string>();

            if (expected.Id != null && DiffCreatureCardId(given.GetId(), expected.Id) != "")
            {
                result.Add(DiffCreatureCardId(given.GetId(), expected.Id, $"{path}id."));
            }

            return string.Join("\n", result);
        }
    }
}
