// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace GameModule.Api {
    public interface GameApi {
        Game StartGame();

        Game PlayCard(CreatureCardId cardId, RowType row);

        Game MoveCard(CreatureCardId cardId, RowType from, RowType to);
    }
}