// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using HttpClientModule.Api;
using GameSetup.Api;
using GameComponents.Api;

namespace GameSetup.Web {
    public class GameSetupApiWebClient: GameSetupApi {
        readonly HttpClient client;

        public GameSetupApiWebClient(
            HttpClientFactory factory,
            GameSetupWebClientConfig config
        ) {
            this.client = factory.Create(config.Value);
        }
        public Game StartGame() {
            return client.Post("/gameSetupApi/startGame", Optional<object>.Empty()).GetBody<GameSetupApiStartGameResponse>().Get().Value;
        }
        public Game PlayCard(CreatureCardId cardId, RowType row) {
            return client.Post("/gameSetupApi/playCard", Optional<GameSetupApiPlayCardRequest>.Of(GameSetupApiPlayCardRequest.Create(cardId, row))).GetBody<GameSetupApiPlayCardResponse>().Get().Value;
        }
        public Game MoveCard(CreatureCardId cardId, RowType from, RowType to) {
            return client.Post("/gameSetupApi/moveCard", Optional<GameSetupApiMoveCardRequest>.Of(GameSetupApiMoveCardRequest.Create(cardId, from, to))).GetBody<GameSetupApiMoveCardResponse>().Get().Value;
        }
    }
}