// DO NOT EDIT! Autogenerated by HLA tool

using System.Collections.Generic;
using B20.Architecture.Exceptions;
using B20.Ext;

namespace Serialization.Api {
    public class DeserializationException : ApiException
    {
        public DeserializationException(string message) : base(message)
        {
        }
    }

    public interface Serializer
    {
        SerializedValue Serialize(object value);

        T Deserialize<T>(SerializedValue serializedValue);

        List<T> DeserializeList<T>(SerializedValue serializedValue);
    }
}