// DO NOT EDIT! Autogenerated by HLA tool

using System.Collections.Generic;
using B20.Ext;

namespace Serialization.Api {
    public interface Serializer {
        SerializedValue Serialize(object value);
    }
}