// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.singlegame.api

import com.github.bratek20.architecture.exceptions.ApiException

class GameNotFoundException(
    message: String = ""
): ApiException(message) {
}