// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.singlegame.api

import com.github.bratek20.ostium.gamesmanagement.api.*
import com.github.bratek20.ostium.user.api.*

interface SingleGameApi {
    @Throws(
        GameNotFoundException::class,
    )
    fun getState(gameId: GameId, user: Username): GameState

    fun playCard(gameId: GameId, user: Username, cardId: CreatureCardId, row: RowType): GameState

    fun moveCard(gameId: GameId, user: Username, cardId: CreatureCardId, from: RowType, to: RowType): GameState
}