// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using KaijuGame.Api;

namespace CardDrawing.Api {
    public interface CardDrawer {
        Card Draw();
    }

    public interface CardDrawerFactory {
        CardDrawer Create();
    }
}