// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.user.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.ostium.user.api.*

fun assertUsername(given: Username, expected: String) {
    val diff = diffUsername(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertUserData(given: UserData, expectedInit: ExpectedUserData.() -> Unit) {
    val diff = diffUserData(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}