// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.user.fixtures

import com.github.bratek20.ostium.user.api.*

fun diffUsername(given: Username, expected: String, path: String = ""): String {
    if (given.value != expected) { return "${path}value ${given.value} != ${expected}" }
    return ""
}

data class ExpectedUserData(
    var name: String? = null,
)
fun diffUserData(given: UserData, expectedInit: ExpectedUserData.() -> Unit, path: String = ""): String {
    val expected = ExpectedUserData().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.name?.let {
        if (diffUsername(given.getName(), it) != "") { result.add(diffUsername(given.getName(), it, "${path}name.")) }
    }

    return result.joinToString("\n")
}