// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesetup.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientFactory

import com.github.bratek20.ostium.gamesetup.api.*

import com.github.bratek20.ostium.gamecomponents.api.*

class GameSetupApiWebClient(
    factory: HttpClientFactory,
    config: GameSetupWebClientConfig,
): GameSetupApi {
    private val client = factory.create(config.value)

    override fun startGame(): Game {
        return client.post("/gameSetupApi/startGame", null).getBody(GameSetupApiStartGameResponse::class.java).value
    }

    override fun playCard(cardId: CreatureCardId, row: RowType): Game {
        return client.post("/gameSetupApi/playCard", GameSetupApiPlayCardRequest.create(cardId, row)).getBody(GameSetupApiPlayCardResponse::class.java).value
    }

    override fun moveCard(cardId: CreatureCardId, from: RowType, to: RowType): Game {
        return client.post("/gameSetupApi/moveCard", GameSetupApiMoveCardRequest.create(cardId, from, to)).getBody(GameSetupApiMoveCardResponse::class.java).value
    }
}

