// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.kaijugame.api
enum class DamageType {
    Light,
    Medium,
    Heavy,
}

enum class TurnPhase {
    PlayCard,
    AssignDamage,
    AssignGuard,
    Reveal,
}

enum class HitZonePosition {
    Left,
    Center,
    Right,
}