// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamecomponents.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.ostium.gamecomponents.api.*

fun assertGateDurabilityMarker(given: GateDurabilityMarker, expected: Int) {
    val diff = diffGateDurabilityMarker(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}


fun assertCreatureCardId(given: CreatureCardId, expected: String) {
    val diff = diffCreatureCardId(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertCreatureCard(given: CreatureCard, expectedInit: ExpectedCreatureCard.() -> Unit) {
    val diff = diffCreatureCard(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertGateCard(given: GateCard, expectedInit: ExpectedGateCard.() -> Unit) {
    val diff = diffGateCard(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertGateDurabilityCard(given: GateDurabilityCard, expectedInit: ExpectedGateDurabilityCard.() -> Unit) {
    val diff = diffGateDurabilityCard(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}