// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesmanagement.context

import com.github.bratek20.architecture.context.api.ContextBuilder
import com.github.bratek20.architecture.context.api.ContextModule
import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig
import com.github.bratek20.infrastructure.httpserver.api.WebServerModule

import com.github.bratek20.ostium.gamesmanagement.api.*
import com.github.bratek20.ostium.gamesmanagement.web.*

class CreatedGamesWebClient(
    private val config: HttpClientConfig
): ContextModule {
    override fun apply(builder: ContextBuilder) {
        builder
            .setImplObject(CreatedGamesWebClientConfig::class.java, CreatedGamesWebClientConfig(config))
            .setImpl(CreatedGamesApi::class.java, CreatedGamesApiWebClient::class.java)
    }
}

class CreatedGamesWebServer: WebServerModule {
    override fun getImpl(): ContextModule {
        return CreatedGamesImpl()
    }

    override fun getControllers(): List<Class<*>> {
        return listOf(
            CreatedGamesApiController::class.java,
        )
    }
}