// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesmanagement.context

import com.github.bratek20.architecture.context.api.ContextBuilder
import com.github.bratek20.architecture.context.api.ContextModule
import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig
import com.github.bratek20.infrastructure.httpserver.api.WebServerModule

import com.github.bratek20.ostium.gamesmanagement.api.*
import com.github.bratek20.ostium.gamesmanagement.web.*

class GamesManagementWebClient(
    private val config: HttpClientConfig
): ContextModule {
    override fun apply(builder: ContextBuilder) {
        builder
            .setImplObject(GamesManagementWebClientConfig::class.java, GamesManagementWebClientConfig(config))
            .setImpl(GamesManagementApi::class.java, GamesManagementApiWebClient::class.java)
    }
}

class GamesManagementWebServer: WebServerModule {
    override fun apply(builder: ContextBuilder) {
        builder.withModule(GamesManagementImpl())
    }

    override fun getControllers(): List<Class<*>> {
        return listOf(
            GamesManagementApiController::class.java,
        )
    }
}