// DO NOT EDIT! Autogenerated by HLA tool

using System.Collections.Generic;

public class Table
{
    private GateDurabilityCard gateDurabilityCard;
    private CreatureCard? attackRow;
    private CreatureCard? defenseRow;
    private GateCard gateCard;

    private Table(GateDurabilityCard gateDurabilityCard, CreatureCard? attackRow, CreatureCard? defenseRow, GateCard gateCard)
    {
        this.gateDurabilityCard = gateDurabilityCard;
        this.attackRow = attackRow;
        this.defenseRow = defenseRow;
        this.gateCard = gateCard;
    }

    public GateDurabilityCard GetGateDurabilityCard()
    {
        return this.gateDurabilityCard;
    }

    public CreatureCard? GetAttackRow()
    {
        return this.attackRow;
    }

    public CreatureCard? GetDefenseRow()
    {
        return this.defenseRow;
    }

    public GateCard GetGateCard()
    {
        return this.gateCard;
    }

    public static Table Create(GateDurabilityCard gateDurabilityCard, CreatureCard? attackRow, CreatureCard? defenseRow, GateCard gateCard)
    {
        return new Table(gateDurabilityCard, attackRow, defenseRow, gateCard);
    }
}

public class Hand
{
    private List<CreatureCard> cards;

    private Hand(List<CreatureCard> cards)
    {
        this.cards = cards;
    }

    public List<CreatureCard> GetCards()
    {
        return this.cards;
    }

    public static Hand Create(List<CreatureCard> cards)
    {
        return new Hand(cards);
    }
}

public class Game
{
    private Table table;
    private Hand hand;

    private Game(Table table, Hand hand)
    {
        this.table = table;
        this.hand = hand;
    }

    public Table GetTable()
    {
        return this.table;
    }

    public Hand GetHand()
    {
        return this.hand;
    }

    public static Game Create(Table table, Hand hand)
    {
        return new Game(table, hand);
    }
}