Enums
    BlueprintType
        UiElement
        Window
        
ValueObjects
    PrefabChildBlueprint
        name: string
        viewType: string

    PrefabBlueprint
        blueprintType: BlueprintType
        name: string
        viewType: string
        creationOrder: int
        children: PrefabChildBlueprint[]

Interfaces
    PrefabCreatorApi
        startModulePrefabs(modulesPath: string, moduleName: string)
        deleteModulePrefabs(modulesPath: string, moduleName: string)