// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.kajiugame.api

import com.github.bratek20.ostium.gamesmanagement.api.*

interface GameApi {
    @Throws(
        GameNotFoundException::class,
    )
    fun getState(token: GameToken): GameState

    fun endPhase(token: GameToken): GameState

    fun playCard(token: GameToken, handCardIdx: Int): GameState
}