// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.singlegame.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientFactory

import com.github.bratek20.ostium.singlegame.api.*

import com.github.bratek20.ostium.gamesmanagement.api.*
import com.github.bratek20.ostium.user.api.*

class SingleGameApiWebClient(
    factory: HttpClientFactory,
    config: SingleGameWebClientConfig,
): SingleGameApi {
    private val client = factory.create(config.value)

    override fun getState(gameId: GameId, user: Username): GameState {
        return client.post("/ostium/singleGameApi/getState", SingleGameApiGetStateRequest.create(gameId, user)).getBody(SingleGameApiGetStateResponse::class.java).value
    }

    override fun playCard(gameId: GameId, user: Username, cardId: CreatureCardId, row: RowType): GameState {
        return client.post("/ostium/singleGameApi/playCard", SingleGameApiPlayCardRequest.create(gameId, user, cardId, row)).getBody(SingleGameApiPlayCardResponse::class.java).value
    }

    override fun moveCard(gameId: GameId, user: Username, cardId: CreatureCardId, from: RowType, to: RowType): GameState {
        return client.post("/ostium/singleGameApi/moveCard", SingleGameApiMoveCardRequest.create(gameId, user, cardId, from, to)).getBody(SingleGameApiMoveCardResponse::class.java).value
    }
}

