// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.game.api

interface GameApi {
    fun startGame(): Game

    fun playCard(cardId: CreatureCardId, row: RowType): Game

    fun moveCard(cardId: CreatureCardId, from: RowType, to: RowType): Game
}