// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesmanagement.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientFactory

import com.github.bratek20.ostium.gamesmanagement.api.*

import com.github.bratek20.ostium.user.api.*

class CreatedGamesApiWebClient(
    factory: HttpClientFactory,
    config: CreatedGamesWebClientConfig,
): CreatedGamesApi {
    private val client = factory.create(config.value)

    override fun getAll(): List<CreatedGame> {
        return client.post("/createdGamesApi/getAll", null).getBody(CreatedGamesApiGetAllResponse::class.java).value
    }

    override fun create(creator: Username): GameId {
        return client.post("/createdGamesApi/create", CreatedGamesApiCreateRequest.create(creator)).getBody(CreatedGamesApiCreateResponse::class.java).value
    }
}

