// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesmanagement.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig

import com.github.bratek20.ostium.gamesmanagement.api.*

import com.github.bratek20.ostium.user.api.*

class GamesManagementWebClientConfig(
    val value: HttpClientConfig
) {
}
class GamesManagementApiCreateRequest(
    private val creator: String
) {
    fun getCreator(): Username {
        return Username(creator)
    }
    companion object {
        fun create(creator: Username): GamesManagementApiCreateRequest {
            return GamesManagementApiCreateRequest(creator.value)
        }
    }
}
class GamesManagementApiCreateResponse(
    val value: GameId
) {
}
class GamesManagementApiJoinRequest(
    private val joiner: String,
    private val gameId: Int
) {
    fun getJoiner(): Username {
        return Username(joiner)
    }
    fun getGameId(): GameId {
        return GameId(gameId)
    }
    companion object {
        fun create(joiner: Username, gameId: GameId): GamesManagementApiJoinRequest {
            return GamesManagementApiJoinRequest(joiner.value, gameId.value)
        }
    }
}
class GamesManagementApiDeleteRequest(
    private val gameId: Int
) {
    fun getGameId(): GameId {
        return GameId(gameId)
    }
    companion object {
        fun create(gameId: GameId): GamesManagementApiDeleteRequest {
            return GamesManagementApiDeleteRequest(gameId.value)
        }
    }
}
class GamesManagementApiGetAllCreatedResponse(
    val value: List<CreatedGame>
) {
}