// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace HttpClientModule.Api {
    public enum HttpMethod {
        GET,
        POST,
    }
}