// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Architecture.Exceptions;

namespace HttpClientModule.Api {
    public class HttpRequesterException: ApiException {
        public HttpRequesterException(
            string message = ""
        ): base(message) {
        }
    }
}