// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace HttpClientModule.Api {
    public interface HttpClientFactory {
        HttpClient Create(HttpClientConfig config);
    }

    public interface HttpRequester {
        /// <exception cref="HttpRequesterException"/>
        string Send(HttpRequest request);
    }
}