// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Architecture.Contexts.Api;
using B20.Frontend.Windows.Api;
using GamesManagement.Api;
using GamesManagement.ViewModel;
using User.Api;

namespace GamesManagement.Context {
    public class GamesManagementViewModel: ContextModule {
        public void Apply(ContextBuilder builder) {
            builder
                .SetClass<CreatedGameVm>(InjectionMode.Prototype)
                .SetClass<CreatedGameVmGroup>(InjectionMode.Prototype)
                .AddImpl<Window, GamesManagementWindow>();
        }
    }
}