// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Architecture.Contexts.Api;
using B20.Ext;
using GamesManagement.Api;
using GamesManagement.Web;
using HttpClientModule.Api;
using User.Api;

namespace GamesManagement.Context {
    public class GamesManagementWebClient: ContextModule {
        readonly HttpClientConfig config;

        public GamesManagementWebClient(
            HttpClientConfig config
        ) {
            this.config = config;
        }
        public void Apply(ContextBuilder builder) {
            builder
                .SetImplObject<GamesManagementWebClientConfig>(new GamesManagementWebClientConfig(config))
                .SetImpl<GamesManagementApi, GamesManagementApiWebClient>();
        }
    }
}