ValueObjects    
    CreatedGame
        id: GameId: int
        creator: Username
        
Interfaces
    CreatedGamesApi
        getAll(): CreatedGame[]
        
        create(creator: Username): GameId

ViewModels
    CreatedGameVm (clickable)
        main -> CreatedGame
            id (debug)
            creator
            
Windows
    CreatedGamesWindow
        createdGames: ElementList<CreatedGameVm>
        createGame: Button -> GameWindow