ValueObjects    
    CreatedGame
        id: GameId: int
        creator: Username
        
Interfaces
    CreatedGamesApi
        getAll(): CreatedGame[]
        
        create(creator: Username): GameId

Web
    Http
        ExposedInterfaces
            CreatedGamesApi

//ViewModel
    //Elements
        //CreatedGameVm (clickable)
            //main -> CreatedGame
                //id (debug)
                //creator
            
    //Windows
        //CreatedGamesWindow
            //createdGames: CreatedGameVm[]
            //createGame: CreateGameButton: Button -> GameWindow