ValueObjects
    GameId: int

    GameToken
        gameId: GameId
        username: Username

    CreatedGame
        id: GameId
        creator: Username
        joiner: Username?
        
Interfaces
    GamesManagementApi
        create(creator: Username): GameToken

        join(joiner: Username, gameId: GameId): GameToken

        delete(gameId: GameId): void
        
        getAllCreated(): CreatedGame[]

Web
    Http
        ExposedInterfaces
            GamesManagementApi
        urlPathPrefix = "/ostium"

ViewModel
    Elements
        CreatedGameVm (clickable)
            CreatedGame
                id //(debug)
                creator
                //joiner
            delete: Button
    
    Windows
        GamesManagementWindow
            State
                username: Username
            createdGames: CreatedGameVm[]
            createGame: Button