Enums
    RowType
        ATTACK
        DEFENSE

ValueObjects
    CreatureCard
        id: CreatureCardId: string

    GateCard
        destroyed: bool

    GateDurabilityMarker: int
    GateDurabilityCard
        myMarker: GateDurabilityMarker
        opponentMarker: GateDurabilityMarker
    
    Row
        card: CreatureCard?
        
    Table
        gateDurabilityCard: GateDurabilityCard
        attackRow: Row
        defenseRow: Row
        gateCard: GateCard
    
    Hand
        cards: CreatureCard[]
    
    Game
        table: Table
        hand: Hand

Interfaces
    GameSetupApi
        startGame(): Game
        playCard(cardId: CreatureCardId, row: RowType): Game
        moveCard(cardId: CreatureCardId, from: RowType, to: RowType): Game

Web
    Http
        ExposedInterfaces
            GameSetupApi
                                
ViewModels
    CreatureCardVm
        CreatureCard
            id -> name    
        visible: BoolSwitch
    
    RowVm
        Row
            card
    
    TableVm
        Table
            attackRow
            defenseRow
            
    HandVm
        Hand
            cards
            
    GameVm    
        Game
            table
            hand    

Windows
    GameWindow
        game: GameVm