Enums
    DamageType
        Light
        Medium
        Heavy

    TurnPhase
        PlayCard
        AssignDamage
        AssignGuard
        Reveal

    HitZonePosition
        Left
        Center
        Right


ValueObjects
    AttackReceiver
        type: DamageType
        myDamage: int
        opponentDamage: int

    AttackGiver
        type: DamageType
        damageValue: int

    PlayerSide
        pool: AttackPool
        playedCards: Card[]

    HitZone
        position: HitZonePosition
        lightReceiver: AttackReceiver
        mediumReceiver: AttackReceiver
        heavyReceiver: AttackReceiver

    AttackPool
        lightGiver: AttackGiver
        mediumGiver: AttackGiver
        heavyGiver: AttackGiver
        focusLeft: int

    Table
        leftZone: HitZone
        centerZone: HitZone
        rightZone: HitZone

        mySide: PlayerSide
        opponentSide: PlayerSide

    Card
        type: DamageType
        value: int
        focusCost: int

    Hand
        cards: Card[]

    GameState
        turn: int
        phase: TurnPhase
        table: Table
        hand: Hand
        myReady: bool
        opponentReady: bool

Interfaces
    GameApi
        getState(token: GameToken): GameState
            throws
                GameNotFoundException

        // for all phases
        endPhase(token: GameToken): GameState

        //TurnPhase.PlayCard
        playCard(token: GameToken, handCardIdx: int): GameState

        //TurnPhase.AssignDamage
        assignDamage(token: GameToken, zone: HitZonePosition, damageType: DamageType): GameState

        //TurnPhase.AssignGuard
        assignGuard(token: GameToken, zone: HitZonePosition, damageType: DamageType): GameState


Web
    Http
        ExposedInterfaces
            GameApi
        urlPathPrefix = "/ostium"

ViewModel
    Elements
        AttackReceiverVm
            AttackReceiver
                type
                myDamage
                opponentDamage
    
        AttackGiverVm
            AttackGiver
                type
                damageValue
        
        PlayerSideVm
            PlayerSide
                pool
                playedCards
        
        HitZoneVm
            HitZone
                position
                lightReceiver
                mediumReceiver
                heavyReceiver
        
        AttackPoolVm
            AttackPool
                lightGiver
                mediumGiver
                heavyGiver
                focusLeft
        
        TableVm
            Table
                leftZone
                centerZone
                rightZone
        
                mySide
                opponentSide
        
        CardVm
            Card
                type
                value
                focusCost
        
        HandVm
            Hand
                cards
        
        GameStateVm
            GameState
                turn
                phase
                table
                hand
                myReady
                opponentReady
    
    Windows
        GameWindow
            State
                token: GameToken
            gameState: GameStateVm
            endPhaseButton: Button
