Enums
    DamageType
        Light
        Medium
        Heavy

    TurnPhase
        PlayCard
        AssignDamage
        AssignGuard
        Reveal


ValueObjects
    AttackReceiver
        type: DamageType
        myDamage: int
        opponentDamage: int

    AttackGiver
        type: DamageType
        damageValue: int

    PlayerSide
        pool: AttackPool
        playedCards: Card[]

    HitZone
        leftReceiver: AttackReceiver
        centerReceiver: AttackReceiver
        rightReceiver: AttackReceiver

    AttackPool
        lightGiver: AttackGiver
        mediumGiver: AttackGiver
        heavyGiver: AttackGiver
        focusLeft: int

    Table
        leftZone: HitZone
        centerZone: HitZone
        rightZone: HitZone

        mySide: PlayerSide
        opponentSide: PlayerSide

    Card
        type: DamageType
        value: int
        focusCost: int

    Hand
        cards: Card[]

    GameState
        turn: int
        phase: TurnPhase
        table: Table
        hand: Hand
        myReady: bool
        opponentReady: bool

Interfaces
    GameApi
        getState(token: GameToken): GameState
            throws
                GameNotFoundException

        // for all phases
        endPhase(token: GameToken): GameState

        //TurnPhase.PlayCard
        playCard(token: GameToken, handCardIdx: int): GameState

        //assignDamage(...): GameState
        //assignGuard(...): GameState


