//Dependencies
    //GamesManagement (Impl)

Enums
    RowType
        ATTACK
        DEFENSE

ValueObjects
    CreatureCard
        id: CreatureCardId: string
    
    Row
        type: RowType
        card: CreatureCard?
        
    PlayerSide
        attackRow: Row
        defenseRow: Row
        
    Table
        mySide: PlayerSide
        opponentSide: PlayerSide
    
    Hand
        cards: CreatureCard[]
    
    GameState
        table: Table
        myHand: Hand
        opponentHand: Hand
        myName: Username
        opponentName: Username?
            
Interfaces        
    SingleGameApi
        getState(gameId: GameId, user: Username): GameState
            throws
                GameNotFoundException
          
        playCard(gameId: GameId, user: Username, cardId: CreatureCardId, row: RowType): GameState

        moveCard(gameId: GameId, user: Username, cardId: CreatureCardId, from: RowType, to: RowType): GameState

Web
    Http
        ExposedInterfaces
            SingleGameApi
        urlPathPrefix = "/ostium"

ViewModel
    Elements
        CreatureCardVm (withPosition2d, draggable)
            CreatureCard
                id // -> name
            selected: BoolSwitch
        
        RowVm (withRect)
            Row
               card
        
        PlayerSideVm
            PlayerSide
                attackRow
                defenseRow
                
        TableVm
            Table
                mySide
                opponentSide
                
        HandVm
            Hand
                cards
                
        GameStateVm
            GameState
                opponentName
                opponentHand
                table
                myHand
                myName
    
    Windows                
        GameWindow
            State
                user: Username
                gameId: GameId
            gameState: GameStateVm