// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesmanagement.api

import com.github.bratek20.ostium.user.api.*

interface GamesManagementApi {
    fun create(creator: Username): GameId

    fun join(joiner: Username, gameId: GameId): Unit

    fun getAllCreated(): List<CreatedGame>
}