// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesmanagement.api

import com.github.bratek20.ostium.user.api.*

data class GameId(
    val value: Int
) {
    override fun toString(): String {
        return value.toString()
    }

    operator fun plus(other: GameId): GameId {
        return GameId(this.value + other.value)
    }

    operator fun minus(other: GameId): GameId {
        return GameId(this.value - other.value)
    }

    operator fun times(amount: Int): GameId {
        return GameId(this.value * amount)
    }
}

data class GameToken(
    private val gameId: Int,
    private val username: String,
) {
    fun getGameId(): GameId {
        return GameId(this.gameId)
    }

    fun getUsername(): Username {
        return Username(this.username)
    }

    companion object {
        fun create(
            gameId: GameId,
            username: Username,
        ): GameToken {
            return GameToken(
                gameId = gameId.value,
                username = username.value,
            )
        }
    }
}

data class CreatedGame(
    private val id: Int,
    private val creator: String,
    private val joiner: String?,
) {
    fun getId(): GameId {
        return GameId(this.id)
    }

    fun getCreator(): Username {
        return Username(this.creator)
    }

    fun getJoiner(): Username? {
        return this.joiner?.let { it -> Username(it) }
    }

    companion object {
        fun create(
            id: GameId,
            creator: Username,
            joiner: Username?,
        ): CreatedGame {
            return CreatedGame(
                id = id.value,
                creator = creator.value,
                joiner = joiner?.let { it -> it.value },
            )
        }
    }
}