// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace PrefabCreator.Api {
    public interface PrefabCreatorApi {
        void StartModule();
    }
}