// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace PrefabCreator.Api {
    public class PrefabChildBlueprint {
        readonly string name;
        readonly string viewType;

        public PrefabChildBlueprint(
            string name,
            string viewType
        ) {
            this.name = name;
            this.viewType = viewType;
        }
        public string GetName() {
            return name;
        }
        public string GetViewType() {
            return viewType;
        }
        public static PrefabChildBlueprint Create(string name, string viewType) {
            return new PrefabChildBlueprint(name, viewType);
        }
    }

    public class PrefabBlueprint {
        readonly string name;
        readonly string viewType;
        readonly List<PrefabChildBlueprint> children;

        public PrefabBlueprint(
            string name,
            string viewType,
            List<PrefabChildBlueprint> children
        ) {
            this.name = name;
            this.viewType = viewType;
            this.children = children;
        }
        public string GetName() {
            return name;
        }
        public string GetViewType() {
            return viewType;
        }
        public List<PrefabChildBlueprint> GetChildren() {
            return children;
        }
        public static PrefabBlueprint Create(string name, string viewType, List<PrefabChildBlueprint> children) {
            return new PrefabBlueprint(name, viewType, children);
        }
    }
}