// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace PrefabCreator.Api {
    public class PrefabChildBlueprint {
        public static PrefabChildBlueprint Create() {
            return new PrefabChildBlueprint();
        }
    }

    public class PrefabBlueprint {
        readonly string prefabName;
        readonly string viewType;
        readonly List<PrefabChildBlueprint> children;

        public PrefabBlueprint(
            string prefabName,
            string viewType,
            List<PrefabChildBlueprint> children
        ) {
            this.prefabName = prefabName;
            this.viewType = viewType;
            this.children = children;
        }
        public string GetPrefabName() {
            return prefabName;
        }
        public string GetViewType() {
            return viewType;
        }
        public List<PrefabChildBlueprint> GetChildren() {
            return children;
        }
        public static PrefabBlueprint Create(string prefabName, string viewType, List<PrefabChildBlueprint> children) {
            return new PrefabBlueprint(prefabName, viewType, children);
        }
    }
}