// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace PrefabCreator.Api {
    public class PrefabChildBlueprint {
        readonly string prefabPath;
        readonly string viewType;
        readonly string name;

        public PrefabChildBlueprint(
            string prefabPath,
            string viewType,
            string name
        ) {
            this.prefabPath = prefabPath;
            this.viewType = viewType;
            this.name = name;
        }
        public string GetPrefabPath() {
            return prefabPath;
        }
        public string GetViewType() {
            return viewType;
        }
        public string GetName() {
            return name;
        }
        public static PrefabChildBlueprint Create(string prefabPath, string viewType, string name) {
            return new PrefabChildBlueprint(prefabPath, viewType, name);
        }
    }

    public class PrefabBlueprint {
        readonly string prefabName;
        readonly string viewType;
        readonly List<PrefabChildBlueprint> children;

        public PrefabBlueprint(
            string prefabName,
            string viewType,
            List<PrefabChildBlueprint> children
        ) {
            this.prefabName = prefabName;
            this.viewType = viewType;
            this.children = children;
        }
        public string GetPrefabName() {
            return prefabName;
        }
        public string GetViewType() {
            return viewType;
        }
        public List<PrefabChildBlueprint> GetChildren() {
            return children;
        }
        public static PrefabBlueprint Create(string prefabName, string viewType, List<PrefabChildBlueprint> children) {
            return new PrefabBlueprint(prefabName, viewType, children);
        }
    }
}