// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace B20.Architecture.Contexts.Api {
    public enum InjectionMode {
        Singleton,
        Prototype,
    }
}