// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using GamesManagement.Api;
using User.Api;

namespace SingleGame.Api {
    public enum RowType {
        ATTACK,
        DEFENSE,
    }
}