// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using GamesManagement.Api;
using User.Api;

namespace SingleGame.Api {
    public interface SingleGameApi {
        /// <exception cref="GameNotFoundException"/>
        GameState GetState(GameId gameId, Username user);

        GameState PlayCard(GameId gameId, Username user, CreatureCardId cardId, RowType row);

        GameState MoveCard(GameId gameId, Username user, CreatureCardId cardId, RowType from, RowType to);
    }
}