// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace SingleGame.Api {
    public interface SingleGameApi {
        GameState StartGame();

        GameState PlayCard(CreatureCardId cardId, RowType row);

        GameState MoveCard(CreatureCardId cardId, RowType from, RowType to);
    }
}