// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.game.context

import com.github.bratek20.architecture.context.api.ContextBuilder
import com.github.bratek20.architecture.context.api.ContextModule
import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig
import com.github.bratek20.infrastructure.httpserver.api.WebServerModule

import com.github.bratek20.ostium.game.api.*
import com.github.bratek20.ostium.game.web.*

class GameWebClient(
    private val config: HttpClientConfig
): ContextModule {
    override fun apply(builder: ContextBuilder) {
        builder
            .setImplObject(GameWebClientConfig::class.java, GameWebClientConfig(config))
            .setImpl(GameApi::class.java, GameApiWebClient::class.java)
    }
}

class GameWebServer: WebServerModule {
    override fun getImpl(): ContextModule {
        return GameImpl()
    }

    override fun getControllers(): List<Class<*>> {
        return listOf(
            GameApiController::class.java,
        )
    }
}