// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesetup.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.ostium.gamecomponents.api.*
import com.github.bratek20.ostium.gamecomponents.fixtures.*

import com.github.bratek20.ostium.gamesetup.api.*

fun assertHand(given: Hand, expectedInit: ExpectedHand.() -> Unit) {
    val diff = diffHand(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertTable(given: Table, expectedInit: ExpectedTable.() -> Unit) {
    val diff = diffTable(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertGame(given: Game, expectedInit: ExpectedGame.() -> Unit) {
    val diff = diffGame(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}