// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesetup.fixtures

import com.github.bratek20.ostium.gamecomponents.api.*
import com.github.bratek20.ostium.gamecomponents.fixtures.*

import com.github.bratek20.ostium.gamesetup.api.*

data class HandDef(
    var cards: List<(CreatureCardDef.() -> Unit)> = emptyList(),
)
fun hand(init: HandDef.() -> Unit = {}): Hand {
    val def = HandDef().apply(init)
    return Hand.create(
        cards = def.cards.map { it -> creatureCard(it) },
    )
}

data class TableDef(
    var creatureCard: (CreatureCardDef.() -> Unit) = {},
    var gateCard: (GateCardDef.() -> Unit) = {},
    var gateDurabilityCard: (GateDurabilityCardDef.() -> Unit) = {},
)
fun table(init: TableDef.() -> Unit = {}): Table {
    val def = TableDef().apply(init)
    return Table.create(
        creatureCard = creatureCard(def.creatureCard),
        gateCard = gateCard(def.gateCard),
        gateDurabilityCard = gateDurabilityCard(def.gateDurabilityCard),
    )
}

data class GameDef(
    var hand: (HandDef.() -> Unit) = {},
    var table: (TableDef.() -> Unit) = {},
)
fun game(init: GameDef.() -> Unit = {}): Game {
    val def = GameDef().apply(init)
    return Game.create(
        hand = hand(def.hand),
        table = table(def.table),
    )
}