// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamesetup.fixtures

import com.github.bratek20.ostium.gamecomponents.api.*
import com.github.bratek20.ostium.gamecomponents.fixtures.*

import com.github.bratek20.ostium.gamesetup.api.*

data class ExpectedHand(
    var cards: List<(ExpectedCreatureCard.() -> Unit)>? = null,
)
fun diffHand(given: Hand, expectedInit: ExpectedHand.() -> Unit, path: String = ""): String {
    val expected = ExpectedHand().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.cards?.let {
        if (given.getCards().size != it.size) { result.add("${path}cards size ${given.getCards().size} != ${it.size}"); return@let }
        given.getCards().forEachIndexed { idx, entry -> if (diffCreatureCard(entry, it[idx]) != "") { result.add(diffCreatureCard(entry, it[idx], "${path}cards[${idx}].")) } }
    }

    return result.joinToString("\n")
}

data class ExpectedTable(
    var creatureCard: (ExpectedCreatureCard.() -> Unit)? = null,
    var gateCard: (ExpectedGateCard.() -> Unit)? = null,
    var gateDurabilityCard: (ExpectedGateDurabilityCard.() -> Unit)? = null,
)
fun diffTable(given: Table, expectedInit: ExpectedTable.() -> Unit, path: String = ""): String {
    val expected = ExpectedTable().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.creatureCard?.let {
        if (diffCreatureCard(given.getCreatureCard(), it) != "") { result.add(diffCreatureCard(given.getCreatureCard(), it, "${path}creatureCard.")) }
    }

    expected.gateCard?.let {
        if (diffGateCard(given.getGateCard(), it) != "") { result.add(diffGateCard(given.getGateCard(), it, "${path}gateCard.")) }
    }

    expected.gateDurabilityCard?.let {
        if (diffGateDurabilityCard(given.getGateDurabilityCard(), it) != "") { result.add(diffGateDurabilityCard(given.getGateDurabilityCard(), it, "${path}gateDurabilityCard.")) }
    }

    return result.joinToString("\n")
}

data class ExpectedGame(
    var hand: (ExpectedHand.() -> Unit)? = null,
    var table: (ExpectedTable.() -> Unit)? = null,
)
fun diffGame(given: Game, expectedInit: ExpectedGame.() -> Unit, path: String = ""): String {
    val expected = ExpectedGame().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.hand?.let {
        if (diffHand(given.getHand(), it) != "") { result.add(diffHand(given.getHand(), it, "${path}hand.")) }
    }

    expected.table?.let {
        if (diffTable(given.getTable(), it) != "") { result.add(diffTable(given.getTable(), it, "${path}table.")) }
    }

    return result.joinToString("\n")
}