// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamecomponents.fixtures

import com.github.bratek20.ostium.gamecomponents.api.*

fun gateDurabilityMarker(value: Int = 0): GateDurabilityMarker {
    return GateDurabilityMarker(value)
}

data class CreatureCardDef(
    var name: String = "someValue",
)
fun creatureCard(init: CreatureCardDef.() -> Unit = {}): CreatureCard {
    val def = CreatureCardDef().apply(init)
    return CreatureCard.create(
        name = def.name,
    )
}

data class GateCardDef(
    var destroyed: Boolean = false,
)
fun gateCard(init: GateCardDef.() -> Unit = {}): GateCard {
    val def = GateCardDef().apply(init)
    return GateCard.create(
        destroyed = def.destroyed,
    )
}

data class GateDurabilityCardDef(
    var myMarker: Int = 0,
    var opponentMarker: Int = 0,
)
fun gateDurabilityCard(init: GateDurabilityCardDef.() -> Unit = {}): GateDurabilityCard {
    val def = GateDurabilityCardDef().apply(init)
    return GateDurabilityCard.create(
        myMarker = GateDurabilityMarker(def.myMarker),
        opponentMarker = GateDurabilityMarker(def.opponentMarker),
    )
}