// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamecomponents.fixtures

import com.github.bratek20.ostium.gamecomponents.api.*

fun diffGateDurabilityMarker(given: GateDurabilityMarker, expected: Int, path: String = ""): String {
    if (given.value != expected) { return "${path}value ${given.value} != ${expected}" }
    return ""
}

data class ExpectedCreatureCard(
    var name: String? = null,
)
fun diffCreatureCard(given: CreatureCard, expectedInit: ExpectedCreatureCard.() -> Unit, path: String = ""): String {
    val expected = ExpectedCreatureCard().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.name?.let {
        if (given.getName() != it) { result.add("${path}name ${given.getName()} != ${it}") }
    }

    return result.joinToString("\n")
}

data class ExpectedGateCard(
    var destroyed: Boolean? = null,
)
fun diffGateCard(given: GateCard, expectedInit: ExpectedGateCard.() -> Unit, path: String = ""): String {
    val expected = ExpectedGateCard().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.destroyed?.let {
        if (given.getDestroyed() != it) { result.add("${path}destroyed ${given.getDestroyed()} != ${it}") }
    }

    return result.joinToString("\n")
}

data class ExpectedGateDurabilityCard(
    var myMarker: Int? = null,
    var opponentMarker: Int? = null,
)
fun diffGateDurabilityCard(given: GateDurabilityCard, expectedInit: ExpectedGateDurabilityCard.() -> Unit, path: String = ""): String {
    val expected = ExpectedGateDurabilityCard().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.myMarker?.let {
        if (diffGateDurabilityMarker(given.getMyMarker(), it) != "") { result.add(diffGateDurabilityMarker(given.getMyMarker(), it, "${path}myMarker.")) }
    }

    expected.opponentMarker?.let {
        if (diffGateDurabilityMarker(given.getOpponentMarker(), it) != "") { result.add(diffGateDurabilityMarker(given.getOpponentMarker(), it, "${path}opponentMarker.")) }
    }

    return result.joinToString("\n")
}