// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using HttpClientModule.Api;
using GamesManagement.Api;
using User.Api;

namespace GamesManagement.Web {
    public class GamesManagementWebClientConfig {
        public HttpClientConfig Value { get; }

        public GamesManagementWebClientConfig(
            HttpClientConfig value
        ) {
            Value = value;
        }
    }

    public class GamesManagementApiCreateRequest {
        readonly string creator;

        public GamesManagementApiCreateRequest(
            string creator
        ) {
            this.creator = creator;
        }
        public Username GetCreator() {
            return new Username(creator);
        }
        public static GamesManagementApiCreateRequest Create(Username creator) {
            return new GamesManagementApiCreateRequest(creator.Value);
        }
    }

    public class GamesManagementApiCreateResponse {
        public GameId Value { get; }

        public GamesManagementApiCreateResponse(
            GameId value
        ) {
            Value = value;
        }
    }

    public class GamesManagementApiJoinRequest {
        readonly string joiner;
        readonly int gameId;

        public GamesManagementApiJoinRequest(
            string joiner,
            int gameId
        ) {
            this.joiner = joiner;
            this.gameId = gameId;
        }
        public Username GetJoiner() {
            return new Username(joiner);
        }
        public GameId GetGameId() {
            return new GameId(gameId);
        }
        public static GamesManagementApiJoinRequest Create(Username joiner, GameId gameId) {
            return new GamesManagementApiJoinRequest(joiner.Value, gameId.Value);
        }
    }

    public class GamesManagementApiDeleteRequest {
        readonly int gameId;

        public GamesManagementApiDeleteRequest(
            int gameId
        ) {
            this.gameId = gameId;
        }
        public GameId GetGameId() {
            return new GameId(gameId);
        }
        public static GamesManagementApiDeleteRequest Create(GameId gameId) {
            return new GamesManagementApiDeleteRequest(gameId.Value);
        }
    }

    public class GamesManagementApiGetAllCreatedResponse {
        public List<CreatedGame> Value { get; }

        public GamesManagementApiGetAllCreatedResponse(
            List<CreatedGame> value
        ) {
            Value = value;
        }
    }
}