// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using HttpClientModule.Api;
using GamesManagement.Api;
using User.Api;

namespace CreatedGames.Web {
    public class CreatedGamesApiWebClient: CreatedGamesApi {
        readonly HttpClient client;

        public CreatedGamesApiWebClient(
            HttpClientFactory factory,
            CreatedGamesWebClientConfig config
        ) {
            this.client = factory.Create(config.Value);
        }
        public List<CreatedGame> GetAll() {
            return client.Post("/createdGamesApi/getAll", Optional<object>.Empty()).GetBody<CreatedGamesApiGetAllResponse>().Get().Value;
        }
        public GameId Create(Username creator) {
            return client.Post("/createdGamesApi/create", Optional<CreatedGamesApiCreateRequest>.Of(CreatedGamesApiCreateRequest.Create(creator))).GetBody<CreatedGamesApiCreateResponse>().Get().Value;
        }
    }
}