// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using User.Api;

namespace CreatedGames.Api {
    public interface CreatedGamesApi {
        List<CreatedGame> GetAll();

        GameId Create(Username creator);
    }
}