// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Windows.Api;
using B20.Frontend.UiElements;
using SingleGame.Api;
using GamesManagement.Api;
using User.Api;

namespace SingleGame.ViewModel {
    public class OldGameWindowState {
        public Username User { get; }
        public GameId GameId { get; }

        public OldGameWindowState(
            Username user,
            GameId gameId
        ) {
            User = user;
            GameId = gameId;
        }
    }

    public partial class OldGameWindow: Window<OldGameWindowState> {
        public GameStateVm GameState { get; set; }
    }
}