// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Architecture.Contexts.Api;
using B20.Frontend.Windows.Api;
using KaijuGame.Api;
using KaijuGame.ViewModel;
using GamesManagement.Api;

namespace KaijuGame.Context {
    public class KaijuGameViewModel: ContextModule {
        public void Apply(ContextBuilder builder) {
            builder
                .SetClass<AttackReceiverVm>(InjectionMode.Prototype)
                .SetClass<AttackGiverVm>(InjectionMode.Prototype)
                .SetClass<PlayerSideVm>(InjectionMode.Prototype)
                .SetClass<HitZoneVm>(InjectionMode.Prototype)
                .SetClass<AttackPoolVm>(InjectionMode.Prototype)
                .SetClass<TableVm>(InjectionMode.Prototype)
                .SetClass<CardVm>(InjectionMode.Prototype)
                .SetClass<HandVm>(InjectionMode.Prototype)
                .SetClass<GameStateVm>(InjectionMode.Prototype)
                .SetClass<CardVmGroup>(InjectionMode.Prototype)
                .AddImpl<Window, GameWindow>();
        }
    }
}