// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using KaijuGame.Api;
using GamesManagement.Api;

namespace KaijuGame.Context {
    public class KaijuGameWebClient: ContextModule {
        readonly HttpClientConfig config;

        public KaijuGameWebClient(
            HttpClientConfig config
        ) {
            this.config = config;
        }
        public void Apply(ContextBuilder builder) {
            builder
                .SetImplObject<KaijuGameWebClientConfig>(new KaijuGameWebClientConfig(config))
                .SetImpl<GameApi, GameApiWebClient>();
        }
    }
}