// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using KaijuGame.Api;
using KaijuGame.ViewModel;
using GamesManagement.Api;

namespace KaijuGame.View {
    public class AttackReceiverView: ElementView<AttackReceiverVm> {
        [SerializeField]
        EnumSwitchView type;
        [SerializeField]
        LabelView myDamage;
        [SerializeField]
        LabelView opponentDamage;
        protected override void OnBind() {
            base.OnBind();
            type.Bind(ViewModel.Type);
            myDamage.Bind(ViewModel.MyDamage);
            opponentDamage.Bind(ViewModel.OpponentDamage);
        }
    }
}