// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using KaijuGame.Api;
using KaijuGame.ViewModel;
using GamesManagement.Api;

namespace KaijuGame.View {
    public class AttackPoolView: ElementView<AttackPoolVm> {
        [SerializeField]
        AttackGiverView lightGiver;
        [SerializeField]
        AttackGiverView mediumGiver;
        [SerializeField]
        AttackGiverView heavyGiver;
        [SerializeField]
        LabelView focusLeft;
        protected override void OnBind() {
            base.OnBind();
            lightGiver.Bind(ViewModel.LightGiver);
            mediumGiver.Bind(ViewModel.MediumGiver);
            heavyGiver.Bind(ViewModel.HeavyGiver);
            focusLeft.Bind(ViewModel.FocusLeft);
        }
    }
}