// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using KaijuGame.Api;
using KaijuGame.ViewModel;
using GamesManagement.Api;

namespace KaijuGame.View {
    public class GameWindowView: WindowView<GameWindow> {
        [SerializeField]
        GameStateView gameState;
        [SerializeField]
        ButtonView endPhaseButton;
        protected override void OnBind() {
            base.OnBind();
            gameState.Bind(ViewModel.GameState);
            endPhaseButton.Bind(ViewModel.EndPhaseButton);
        }
    }
}