// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using KaijuGame.Api;
using KaijuGame.ViewModel;
using GamesManagement.Api;

namespace KaijuGame.View {
    public class GameStateView: ElementView<GameStateVm> {
        [SerializeField]
        LabelView turn;
        [SerializeField]
        EnumSwitchView phase;
        [SerializeField]
        TableView table;
        [SerializeField]
        HandView hand;
        [SerializeField]
        BoolSwitchView myReady;
        [SerializeField]
        BoolSwitchView opponentReady;
        protected override void OnBind() {
            base.OnBind();
            turn.Bind(ViewModel.Turn);
            phase.Bind(ViewModel.Phase);
            table.Bind(ViewModel.Table);
            hand.Bind(ViewModel.Hand);
            myReady.Bind(ViewModel.MyReady);
            opponentReady.Bind(ViewModel.OpponentReady);
        }
    }
}