// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using KaijuGame.Api;
using KaijuGame.ViewModel;
using GamesManagement.Api;

namespace KaijuGame.View {
    public class HitZoneView: ElementView<HitZoneVm> {
        [SerializeField]
        EnumSwitchView position;
        [SerializeField]
        AttackReceiverView lightReceiver;
        [SerializeField]
        AttackReceiverView mediumReceiver;
        [SerializeField]
        AttackReceiverView heavyReceiver;
        protected override void OnBind() {
            base.OnBind();
            position.Bind(ViewModel.Position);
            lightReceiver.Bind(ViewModel.LightReceiver);
            mediumReceiver.Bind(ViewModel.MediumReceiver);
            heavyReceiver.Bind(ViewModel.HeavyReceiver);
        }
    }
}