// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using KaijuGame.Api;
using KaijuGame.ViewModel;
using GamesManagement.Api;

namespace KaijuGame.View {
    public class PlayerSideView: ElementView<PlayerSideVm> {
        [SerializeField]
        AttackPoolView pool;
        [SerializeField]
        CardGroupView playedCards;
        protected override void OnBind() {
            base.OnBind();
            pool.Bind(ViewModel.Pool);
            playedCards.Bind(ViewModel.PlayedCards);
        }
    }
}