// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using KaijuGame.Api;
using KaijuGame.ViewModel;
using GamesManagement.Api;

namespace KaijuGame.View {
    public class TableView: ElementView<TableVm> {
        [SerializeField]
        HitZoneView leftZone;
        [SerializeField]
        HitZoneView centerZone;
        [SerializeField]
        HitZoneView rightZone;
        [SerializeField]
        PlayerSideView mySide;
        [SerializeField]
        PlayerSideView opponentSide;
        protected override void OnBind() {
            base.OnBind();
            leftZone.Bind(ViewModel.LeftZone);
            centerZone.Bind(ViewModel.CenterZone);
            rightZone.Bind(ViewModel.RightZone);
            mySide.Bind(ViewModel.MySide);
            opponentSide.Bind(ViewModel.OpponentSide);
        }
    }
}