// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.game.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig

import com.github.bratek20.ostium.game.api.*

class GameWebClientConfig(
    val value: HttpClientConfig
) {
}
class GameApiStartGameResponse(
    val value: Game
) {
}
class GameApiPlayCardRequest(
    private val cardId: String,
    private val row: String
) {
    fun getCardId(): CreatureCardId {
        return CreatureCardId(cardId)
    }
    fun getRow(): RowType {
        return RowType.valueOf(row)
    }
    companion object {
        fun create(cardId: CreatureCardId, row: RowType): GameApiPlayCardRequest {
            return GameApiPlayCardRequest(cardId.value, row.name)
        }
    }
}
class GameApiPlayCardResponse(
    val value: Game
) {
}
class GameApiMoveCardRequest(
    private val cardId: String,
    private val from: String,
    private val to: String
) {
    fun getCardId(): CreatureCardId {
        return CreatureCardId(cardId)
    }
    fun getFrom(): RowType {
        return RowType.valueOf(from)
    }
    fun getTo(): RowType {
        return RowType.valueOf(to)
    }
    companion object {
        fun create(cardId: CreatureCardId, from: RowType, to: RowType): GameApiMoveCardRequest {
            return GameApiMoveCardRequest(cardId.value, from.name, to.name)
        }
    }
}
class GameApiMoveCardResponse(
    val value: Game
) {
}