// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.createdgames.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig

import com.github.bratek20.ostium.createdgames.api.*

import com.github.bratek20.ostium.user.api.*

class CreatedGamesWebClientConfig(
    val value: HttpClientConfig
) {
}
class CreatedGamesApiGetAllResponse(
    val value: List<CreatedGame>
) {
}
class CreatedGamesApiCreateRequest(
    private val creator: String
) {
    fun getCreator(): Username {
        return Username(creator)
    }
    companion object {
        fun create(creator: Username): CreatedGamesApiCreateRequest {
            return CreatedGamesApiCreateRequest(creator.value)
        }
    }
}
class CreatedGamesApiCreateResponse(
    val value: GameId
) {
}