// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.createdgames.web

import com.github.bratek20.architecture.serialization.api.Serializer
import com.github.bratek20.architecture.serialization.api.Struct
import com.github.bratek20.architecture.serialization.context.SerializationFactory

import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

import com.github.bratek20.ostium.createdgames.api.*

@RestController
@RequestMapping("/createdGamesApi")
class CreatedGamesApiController(
    private val api: CreatedGamesApi,
) {
    private val serializer: Serializer = SerializationFactory.createSerializer()

    @PostMapping("/getAll")
    fun getAll(): Struct {
        // no request needed
        return serializer.asStruct(CreatedGamesApiGetAllResponse(api.getAll()))
    }

    @PostMapping("/create")
    fun create(@RequestBody rawRequest: Struct): Struct {
        val request = serializer.fromStruct(rawRequest, CreatedGamesApiCreateRequest::class.java)
        return serializer.asStruct(CreatedGamesApiCreateResponse(api.create(request.getCreator())))
    }
}

