ExternalTypes
    HttpResponse // TODO-REF hla missing generic types support
        //getStatusCode(): Int
        //getBody<T>(type: Class<T>): T
        
ValueObjects
    HttpClientAuth
        value: string (example: "Basic YmFydG9zejpydWR6a2k=")
        //could be added in the future:
        //username: string
        //password: string
    
    HttpClientConfig
       baseUrl: string
       auth: HttpClientAuth? = empty

Enums
    HttpMethod
        GET
        POST
    
Interfaces
    //internal - created by factory 
    HttpClient
        get(path: String): HttpResponse
        post(path: String, body: any?): HttpResponse

    //outgoing 
    HttpClientFactory
        create(config: HttpClientConfig): HttpClient

    //incoming
    HttpRequester
        HttpHeader
            key: string
            value: string
        HttpRequest
            url: string
            method: HttpMethod
            content: string?
            contentType: string
            headers: HttpHeader[]
        send(request: HttpRequest): string
            throws
                HttpRequesterException 