// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using GameComponents.Api;

namespace GameSetup.Api {
    public enum RowType {
        ATTACK,
        DEFENSE,
    }
}