// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using GameComponents.Api;

namespace GameSetup.Api {
    public interface GameSetupApi {
        Game StartGame();

        Game PlayCard(CreatureCardId cardId, RowType row);

        Game MoveCard(CreatureCardId cardId, RowType from, RowType to);
    }
}