// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Windows.Api;
using B20.Frontend.UiElements;
using KaijuGame.Api;
using GamesManagement.Api;

namespace KaijuGame.ViewModel {
    public class GamesWindowState {
        public GameToken Token { get; }

        public GamesWindowState(
            GameToken token
        ) {
            Token = token;
        }
    }

    public partial class GamesWindow: Window<GamesWindowState> {
        public GameStateVm GameState { get; set; }
    }
}