// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using SingleGame.Api;
using SingleGame.ViewModel;
using GamesManagement.Api;
using User.Api;

namespace SingleGame.View {
    public class GameWindowView: WindowView<GameWindow> {
        [SerializeField]
        GameStateView gameState;
        protected override void OnBind() {
            base.OnBind();
            gameState.Bind(ViewModel.GameState);
        }
    }
}