// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using SingleGame.ViewModel;
using GamesManagement.Api;
using User.Api;

namespace SingleGame.View {
    public class HandView: ElementView<HandVm> {
        [SerializeField]
        CreatureCardGroupView cards;
        protected override void OnBind() {
            base.OnBind();
            cards.Bind(ViewModel.Cards);
        }
    }
}