// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using SingleGame.ViewModel;
using GamesManagement.Api;
using SingleGame.Api;
using User.Api;

namespace SingleGame.View {
    public class OptionalCreatureCardView: OptionalUiElementView<CreatureCardView, CreatureCardVm, CreatureCard> {
    }
}