// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using SingleGame.Api;
using SingleGame.ViewModel;
using GamesManagement.Api;
using User.Api;

namespace SingleGame.View {
    public class PlayerSideView: ElementView<PlayerSideVm> {
        [SerializeField]
        RowView attackRow;
        [SerializeField]
        RowView defenseRow;
        protected override void OnBind() {
            base.OnBind();
            attackRow.Bind(ViewModel.AttackRow);
            defenseRow.Bind(ViewModel.DefenseRow);
        }
    }
}