// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using SingleGame.Api;
using SingleGame.ViewModel;
using GamesManagement.Api;
using User.Api;

namespace SingleGame.View {
    public class TableView: ElementView<TableVm> {
        [SerializeField]
        PlayerSideView opponentSide;
        [SerializeField]
        PlayerSideView mySide;
        protected override void OnBind() {
            base.OnBind();
            opponentSide.Bind(ViewModel.OpponentSide);
            mySide.Bind(ViewModel.MySide);
        }
    }
}