// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using SingleGame.ViewModel;
using GamesManagement.Api;
using User.Api;

namespace SingleGame.View {
    public class TableView: ElementView<TableVm> {
        [SerializeField]
        PlayerSideView mySide;
        [SerializeField]
        PlayerSideView opponentSide;
        protected override void OnBind() {
            base.OnBind();
            mySide.Bind(ViewModel.MySide);
            opponentSide.Bind(ViewModel.OpponentSide);
        }
    }
}