// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.gamemodule.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientFactory

import com.github.bratek20.ostium.gamemodule.api.*

class GameApiWebClient(
    factory: HttpClientFactory,
    config: GameModuleWebClientConfig,
): GameApi {
    private val client = factory.create(config.value)

    override fun startGame(): Game {
        return client.post("/gameApi/startGame", null).getBody(GameApiStartGameResponse::class.java).value
    }

    override fun playCard(cardId: CreatureCardId, row: RowType): Game {
        return client.post("/gameApi/playCard", GameApiPlayCardRequest.create(cardId, row)).getBody(GameApiPlayCardResponse::class.java).value
    }

    override fun moveCard(cardId: CreatureCardId, from: RowType, to: RowType): Game {
        return client.post("/gameApi/moveCard", GameApiMoveCardRequest.create(cardId, from, to)).getBody(GameApiMoveCardResponse::class.java).value
    }
}

