// DO NOT EDIT! Autogenerated by HLA tool

using System;
using GameComponents;
using SingleGame.Api;
using Xunit;

namespace SingleGame
{
    public static class Asserts
    {
        public static void AssertTable(Table given, Action<Diffs.ExpectedTable> expectedInit)
        {
            var diff = Diffs.DiffTable(given, expectedInit);
            Assert.True(diff == "", diff);
        }

        public static void AssertHand(Hand given, Action<Diffs.ExpectedHand> expectedInit)
        {
            var diff = Diffs.DiffHand(given, expectedInit);
            Assert.True(diff == "", diff);
        }

        public static void AssertGame(GameState given, Action<Diffs.ExpectedGame> expectedInit)
        {
            var diff = Diffs.DiffGame(given, expectedInit);
            Assert.True(diff == "", diff);
        }
    }
}