// DO NOT EDIT! Autogenerated by HLA tool

using SingleGame.Api;
using Xunit;

namespace SingleGame
{
    public static class SingleGameAsserts
    {
        public static void AssertCreatureCardId(CreatureCardId given, string expected)
        {
            var diff = Diffs.DiffCreatureCardId(given, expected);
            Assert.True(diff == "", diff);
        }
    }
}