// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.user.api

val USER_DATA_DATA_KEY = com.github.bratek20.architecture.data.api.ObjectDataKey(
    "UserData",
    UserData::class
)