// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.ostium.user.api

data class Username(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}