// DO NOT EDIT! Autogenerated by HLA tool

using System.Collections.Generic;
using B20.Architecture.Exceptions;
using B20.Ext;

namespace HttpClient.Api {
    public class HttpRequesterException: ApiException {
        public HttpRequesterException(
            string message = ""
        ): base(message) {
        }
    }
}