// DO NOT EDIT! Autogenerated by HLA tool

using System.Collections.Generic;
using B20.Ext;

namespace HttpClient.Api {
    public interface HttpClient {
        HttpResponse Get(string path);

        HttpResponse Post(string path, Optional<object> body);
    }

    public interface HttpClientFactory {
        HttpClient Create(HttpClientConfig config);
    }

    public interface HttpRequester {
        /// <exception cref="HttpRequesterException"/>
        string Send(HttpRequest request);
    }
}