// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using GamesManagement.Api;
using GamesManagement.ViewModel;
using User.Api;

namespace GamesManagement.View {
    public class CreatedGameGroupView: UiElementGroupView<CreatedGameView, CreatedGameVm, CreatedGame> {
    }
}