// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using GamesManagement.ViewModel;
using User.Api;

namespace GamesManagement.View {
    public class CreatedGameView: ElementView<CreatedGameVm> {
        [SerializeField]
        LabelView id;
        [SerializeField]
        LabelView creator;
        protected override void OnBind() {
            base.OnBind();
            id.Bind(ViewModel.Id);
            creator.Bind(ViewModel.Creator);
        }
    }
}