// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using GamesManagement.Api;
using GamesManagement.ViewModel;
using User.Api;

namespace GamesManagement.View {
    public class GamesManagementWindowView: WindowView<GamesManagementWindow> {
        [SerializeField]
        CreatedGameGroupView createdGames;
        [SerializeField]
        ButtonView createGame;
        protected override void OnBind() {
            base.OnBind();
            createdGames.Bind(ViewModel.CreatedGames);
            createGame.Bind(ViewModel.CreateGame);
        }
    }
}